/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login_sysytem;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JComboBox;

/**
 *
 * @author root
 */
public class Insert extends javax.swing.JFrame {

    /**
     * Creates new form Insert
     */
    public Insert() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        g = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        f = new javax.swing.JComboBox<>();
        a = new javax.swing.JTextField();
        b = new javax.swing.JTextField();
        c = new javax.swing.JTextField();
        d = new javax.swing.JTextField();
        e = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(44, 62, 80));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("City Name :");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(90, 40, 110, 40);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Room-Type :");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(90, 280, 120, 50);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Hall Number :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(90, 90, 120, 40);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Hall Name :");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(90, 140, 120, 40);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Cost :");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(90, 240, 120, 40);

        g.setBackground(new java.awt.Color(192, 192, 192));
        jPanel2.add(g);
        g.setBounds(360, 340, 150, 20);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("Address :");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(90, 190, 120, 40);

        f.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "NON-AC" }));
        jPanel2.add(f);
        f.setBounds(360, 290, 150, 20);

        a.setBackground(new java.awt.Color(192, 192, 192));
        jPanel2.add(a);
        a.setBounds(360, 50, 150, 20);

        b.setBackground(new java.awt.Color(192, 192, 192));
        jPanel2.add(b);
        b.setBounds(360, 100, 150, 20);

        c.setBackground(new java.awt.Color(192, 192, 192));
        jPanel2.add(c);
        c.setBounds(360, 150, 150, 20);

        d.setBackground(new java.awt.Color(192, 192, 192));
        jPanel2.add(d);
        d.setBounds(360, 200, 150, 20);

        e.setBackground(new java.awt.Color(192, 192, 192));
        jPanel2.add(e);
        e.setBounds(360, 250, 150, 20);

        jButton5.setBackground(new java.awt.Color(209, 26, 42));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("CANCEL");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(230, 410, 73, 23);

        submit.setBackground(new java.awt.Color(0, 255, 0));
        submit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        submit.setForeground(new java.awt.Color(255, 255, 255));
        submit.setText("SUBMIT");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel2.add(submit);
        submit.setBounds(340, 410, 77, 23);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("Contact Number :");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(90, 330, 150, 40);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("HOME");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(660, 20, 31, 13);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_sysytem/icon3.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel6);
        jLabel6.setBounds(660, 40, 40, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 40, 720, 450);

        jPanel1.setBackground(new java.awt.Color(248, 148, 6));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Insertion Operation");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(220, 0, 240, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 720, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        a.setText(null);
        b.setText(null);
        c.setText(null);
        d.setText(null);
        e.setText(null);
        f.setSelectedIndex(0);
        g.setText(null);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        String city=a.getText();
        String no=b.getText();
        String name=c.getText();
        String address=d.getText();
        String cost=e.getText();
        String type=f.getSelectedItem().toString();
        String contact=g.getText();
        
        System.out.println("city"+city);
        System.out.println("hall_no"+no);
        System.out.println("name"+name);
        System.out.println("address"+address);
        System.out.println("cost"+cost);
        System.out.println("type"+type);
        System.out.println("contact"+contact);
        

        
            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection con=DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/db","root","pranav");
                PreparedStatement stmt=con.prepareStatement("select * from hall where  hall_no= ?");
                stmt.setString(1,no);
                ResultSet rs=stmt.executeQuery();
                boolean alreadyExists = false;
                while(rs.next()){
                    alreadyExists = true;
                }
                if(alreadyExists == false){
                    String query = " insert into hall (hall_no,hall_name,address,cost,city,contact_no,type)"+" values (?,?,?,?,?,?,?)";
                    PreparedStatement preparedStmt = con.prepareStatement(query);
                    preparedStmt.setString (1,no);
                    preparedStmt.setString (2,name);
                    preparedStmt.setString (3,address);
                    preparedStmt.setString (4,cost);
                    preparedStmt.setString (5,city);
                    preparedStmt.setString (6,contact);
                    preparedStmt.setString (7,type);
                    preparedStmt.execute(); 
                    JOptionPane.showMessageDialog(null, "Hall details added succesfully");
                     
                    this.setVisible(false);
                     Admin_page h= new Admin_page();                
                     h.setVisible(true);
            

                }else{
                    JOptionPane.showMessageDialog(null, "Hall Already Exists");
                     }
                //                while(rs.next()){
                    //                    System.out.println(rs.getInt(1)+"  "+rs.getString(2));
                    //                }
               // con.close();
            }catch(Exception e){
                System.out.println(e);
            }
        
        
    }//GEN-LAST:event_submitActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        Home h = new Home();
        h.setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Insert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a;
    private javax.swing.JTextField b;
    private javax.swing.JTextField c;
    private javax.swing.JTextField d;
    private javax.swing.JTextField e;
    private javax.swing.JComboBox<String> f;
    private javax.swing.JTextField g;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
