/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login_sysytem;
import com.toedter.calendar.JDateChooser;
import javax.swing.*;
import java.awt.*;
import java.sql.*;
import java.text.SimpleDateFormat;

public class Register extends javax.swing.JFrame {
    
    
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        usr = new javax.swing.JTextField();
        pass1 = new javax.swing.JTextField();
        addr = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        bdate = new com.toedter.calendar.JDateChooser();
        jLabel19 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        pass2 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(248, 148, 6));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CREATE ACCOUNT");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(184, 13, 180, 22);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(90, 10, 520, 40);

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setPreferredSize(new java.awt.Dimension(720, 480));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FIRST NAME:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(130, 70, 110, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_sysytem/icon3.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5);
        jLabel5.setBounds(440, 20, 40, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("HOME");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(440, 10, 31, 13);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("  LAST NAME:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(130, 100, 110, 17);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("USERNAME:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(140, 130, 110, 17);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("  PASSWORD:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(130, 160, 110, 17);

        lname.setBackground(new java.awt.Color(108, 112, 137));
        lname.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lname.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lname);
        lname.setBounds(240, 100, 134, 19);

        usr.setBackground(new java.awt.Color(108, 112, 137));
        usr.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        usr.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(usr);
        usr.setBounds(240, 130, 134, 19);

        pass1.setBackground(new java.awt.Color(108, 112, 137));
        pass1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        pass1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(pass1);
        pass1.setBounds(240, 160, 134, 19);

        addr.setBackground(new java.awt.Color(108, 112, 137));
        addr.setForeground(new java.awt.Color(255, 255, 255));
        addr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addrActionPerformed(evt);
            }
        });
        jPanel1.add(addr);
        addr.setBounds(240, 260, 230, 20);

        fname.setBackground(new java.awt.Color(108, 112, 137));
        fname.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        fname.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(fname);
        fname.setBounds(240, 70, 134, 19);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText(" RETYPE PASSWORD:");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(80, 190, 160, 17);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("BIRTH DATE:");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(130, 220, 110, 17);

        bdate.setBackground(new java.awt.Color(108, 112, 137));
        bdate.setForeground(new java.awt.Color(255, 255, 255));
        bdate.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jPanel1.add(bdate);
        bdate.setBounds(240, 220, 190, 30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("ADDRESS:");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(150, 260, 110, 17);

        submit.setBackground(new java.awt.Color(0, 255, 0));
        submit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        submit.setForeground(new java.awt.Color(255, 255, 255));
        submit.setText("SUBMIT");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel1.add(submit);
        submit.setBounds(330, 330, 77, 23);

        pass2.setBackground(new java.awt.Color(108, 112, 137));
        pass2.setForeground(new java.awt.Color(255, 255, 255));
        pass2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass2ActionPerformed(evt);
            }
        });
        jPanel1.add(pass2);
        pass2.setBounds(240, 190, 134, 20);

        jButton5.setBackground(new java.awt.Color(209, 26, 42));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("CANCEL");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(240, 330, 73, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(90, 50, 518, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        Home h = new Home();
        h.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        String f=fname.getText();
        String l=lname.getText();
        String u=usr.getText();
        String p1=pass1.getText();
        String p2=pass2.getText();
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        String sd = dateFormat.format(bdate.getDate());
        String ad=addr.getText();
        
        System.out.println("first name:"+f);
        System.out.println("last name:"+l);
        System.out.println("username:"+u);
        System.out.println("passoword:"+p1);
        System.out.println("confirm:"+p2);
        System.out.println("date :"+sd);
        System.out.println("addr :"+ad);
        
       if( true==p1.equals(p2) ){
            try{  
                Class.forName("com.mysql.jdbc.Driver");  
                Connection con=DriverManager.getConnection(  
                "jdbc:mysql://localhost:3306/db","root","pranav");  
                PreparedStatement stmt=con.prepareStatement("select * from user where  username= ?");  
                stmt.setString(1,u);
                ResultSet rs=stmt.executeQuery();  
                boolean alreadyExists = false;
                while(rs.next()){  
                    alreadyExists = true;
                }  
                if(alreadyExists == false){
                    String query = " insert into user (username,firstname,lastname,password,date,address)"+ " values (?,?,?,?,?,?)";
                    PreparedStatement preparedStmt = con.prepareStatement(query);
                    preparedStmt.setString (1,u);
                    preparedStmt.setString (2,f);
                    preparedStmt.setString (3,l);
                    preparedStmt.setString (4,p1);
                    preparedStmt.setString (5,sd);
                    preparedStmt.setString (6,ad);
                    preparedStmt.execute();
                    JOptionPane.showMessageDialog(null, "Account Created ! Now Log in");                   
                    
                }else{
                    JOptionPane.showMessageDialog(null, "Contact Already Exists");
                }
//                while(rs.next()){
//                    System.out.println(rs.getInt(1)+"  "+rs.getString(2));  
//                }  
                con.close();  
            }catch(Exception e){ 
                System.out.println(e);  
            }  
        }else{
            JOptionPane.showMessageDialog(null, "Please Enter correct details");
        } 
             
    }//GEN-LAST:event_submitActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        fname.setText(null);
        lname.setText(null);
        usr.setText(null);
        pass1.setText(null);
        pass2.setText(null);
        addr.setText(null);
        JDateChooser dateChooser= new JDateChooser();
        dateChooser.setDate(null);
        addr.setText(null);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void addrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addrActionPerformed

    private void pass2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addr;
    private com.toedter.calendar.JDateChooser bdate;
    private javax.swing.JTextField fname;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField pass1;
    private javax.swing.JTextField pass2;
    private javax.swing.JButton submit;
    private javax.swing.JTextField usr;
    // End of variables declaration//GEN-END:variables
}
