/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login_sysytem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author root
 */
public class Update extends javax.swing.JFrame {

    /**
     * Creates new form Update
     */
    public Update() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        submit1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        submit = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(248, 148, 6));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Update operation");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(220, 0, 240, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 720, 40);

        jPanel2.setBackground(new java.awt.Color(44, 62, 80));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        submit1.setBackground(new java.awt.Color(0, 255, 0));
        submit1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        submit1.setForeground(new java.awt.Color(255, 255, 255));
        submit1.setText("SAVE");
        submit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit1ActionPerformed(evt);
            }
        });
        jPanel2.add(submit1);
        submit1.setBounds(300, 370, 90, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel6);
        jLabel6.setBounds(130, 300, 31, 0);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_sysytem/icon3.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel5);
        jLabel5.setBounds(660, 30, 40, 30);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Hall NO", "HALL NAME", "ADDRESS", "COST", "CITY", "CONTACT", "TYPE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(80, 110, 540, 110);

        submit.setBackground(new java.awt.Color(0, 255, 0));
        submit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        submit.setForeground(new java.awt.Color(255, 255, 255));
        submit.setText("view all data");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel2.add(submit);
        submit.setBounds(310, 40, 110, 40);
        jPanel2.add(jTextField2);
        jTextField2.setBounds(430, 250, 90, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("HOME");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(660, 10, 31, 13);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("name");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(130, 250, 31, 13);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("cost");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(380, 250, 31, 13);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("contact");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(111, 310, 50, 13);
        jPanel2.add(jTextField3);
        jTextField3.setBounds(200, 250, 90, 30);
        jPanel2.add(jTextField4);
        jTextField4.setBounds(200, 310, 90, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 40, 720, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit1ActionPerformed
               
        try{  
                Class.forName("com.mysql.jdbc.Driver");  
                Connection con=DriverManager.getConnection(  
                "jdbc:mysql://localhost:3306/db","root","pranav");  
                
                int selectedRow = table.getSelectedRow();
                String no =(String)table.getValueAt(selectedRow,0);
                String name= (String) table.getValueAt(selectedRow,1);
                String contact= (String) table.getValueAt(selectedRow,2);
                String cost= (String) table.getValueAt(selectedRow, 3);
                
                
               /* PreparedStatement stmt = con.prepareStatement(" update hall,status set hall.hall_no=?,hall_name=?,contact_no=?,cost=?,value=? where hall.hall_no=status.hall_no and hall.hall_no=?");
                stmt.setString(6,no);
                stmt.setString(5,status);
                stmt.setString(4,cost);
                stmt.setString(3,contact);
                stmt.setString(2,name);
                stmt.setString(1,no);
                
                int rowAffected = stmt.executeUpdate();
                
                System.out.println("no:"+no);
                System.out.println("name:"+name);
                System.out.println("contact:"+contact);
                System.out.println("cost:"+cost);
                
                
                
                if(rowAffected > 0){
                    JOptionPane.showMessageDialog(null, "Data Updated !");
                     this.setVisible(false);
                     Admin_page h= new Admin_page();                
                     h.setVisible(true);
                        }
                else{
                    JOptionPane.showMessageDialog(null, "Error Updating Data!");
                    }
                con.close();  
           */
            }catch(Exception e){ 
                System.out.println(e);  
                                }
        
        
    }//GEN-LAST:event_submit1ActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        Home h = new Home();
        h.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        String no;
        String contact;
        String name;
        String cost;
        String city;
        String address;
        String type;

        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/db","root","pranav");
            PreparedStatement stmt=con.prepareStatement("select hall.hall_no,hall_name,cost,contact_no from hall,status where hall.hall_no=status.hall_no;");
            ResultSet rs=stmt.executeQuery();
            String[] tblHead={"HALL NUMBER","HALL NAME ","COST","CONTACT NUMBER"};
            DefaultTableModel dtm=new DefaultTableModel(tblHead,0);

            boolean alreadyExists = false;
            while(rs.next()){
                
                alreadyExists = true;
                no=rs.getString(1);
                name= rs.getString(2);
                cost = rs.getString(3);
                contact= rs.getString(4);

                String[] item={no,name,cost,contact};
                dtm.addRow(item);
            }
            if(alreadyExists == false){
                JOptionPane.showMessageDialog(null, "!! Invalid hall number !!");
            }else{
                table.setModel(dtm);
                //
            }

        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_submitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton submit;
    private javax.swing.JButton submit1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
