/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login_sysytem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author root
 */
public class View_record extends javax.swing.JFrame {

    /**
     * Creates new form View_record
     */
    public View_record() {
        initComponents();
        
    }
    
    String username;        //global variable
    public View_record(String usr) {
        initComponents();
       username=usr;
       
       try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/db","root","pranav");
            PreparedStatement stmt=con.prepareStatement("select hall.*,status.date from hall,status where hall.hall_no=status.hall_no and status.username=?;");            
            stmt.setString(1,username);
            ResultSet rs=stmt.executeQuery();
            String[] tblHead={"HALL NO","HALL NAME ","CONTACT NUMBER ","COST","ADDRESS","CITY","TYPE","BOOK DATE"};                               
            DefaultTableModel dtm=new DefaultTableModel(tblHead,0);

            boolean alreadyExists = false;
            while(rs.next()){
                alreadyExists = true;
                
               
                
                String[] item={rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8)};
                dtm.addRow(item);
            }
            if(alreadyExists == false){
                JOptionPane.showMessageDialog(null, "!! NO RECORD FOUND !!");
            }else{
                table.setModel(dtm);                
            }

        }catch(Exception e){
            System.out.println(e);
        }
       
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "HALL NO", "HALL NAME", "CONTACT", "COST", "ADDRESS", "CITY", "TYPE", "DATE OF BOOKING"
            }
        ));
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       //TABLE INSERTION LOGIC
       //*************************
       
       
       
       
       
       
       
       
       
        //************************
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_record().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
